routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::prefix('parent')->name('parent.')->group(function () {
    Route::get('/inactive', 'Parent\DashboardController@inactive')->name('inactive');

    Route::get('/', 'Parent\DashboardController@index')->name('dashboard');

    Route::prefix('children')->group(function () {
        Route::get('/info', 'Parent\ChildrenController@profile')->name('children.profile');
        Route::get('/activities', 'Parent\ChildrenController@activities')->name('children.activities');
        Route::get('/attendances', 'Parent\ChildrenController@attendances')->name('children.attendances'); //Listing
    });

    Route::prefix('pick_ups')->group(function () {
        Route::get('history', 'Parent\PickUpsController@history')->name('pick_ups.history');
        Route::post('{id}/cancel/', 'Parent\PickUpsController@cancel')->name('pick_ups.cancel');
    });

    Route::resource('pick_ups', 'Parent\PickUpsController', ['only' => [
        'create', 'store', 'show'
    ]]);
});

Route::prefix('admin')->group(function () {
    /* Login/Logout */
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    /* Reset Password */
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

    /* Manage Student*/
    Route::resource('students', 'Admin\StudentsController');
    Route::resource('students.activities', 'Admin\StudentsActivitiesController');

    /* Manage Attendance */
    Route::resource('attendances', 'Admin\AttendancesController');

    /* Manage Student Attendances */
    Route::resource('students.attendances', 'Admin\StudentsAttendancesController', ['only' => [
        'index',
    ]]);

    /* Manage Pick Up */
    Route::resource('pick_ups', 'Admin\PickUpsController', [
        'only' => ['index', 'show']
    ]);

    /* Manage Restore Students */
    Route::get('/restoreStudents', 'Admin\RestoreStudentsController@index')->name('restorestudents.index');
    Route::get('/restoreStudents/{student}', 'Admin\RestoreStudentsController@show')->name('restorestudents.show');
    Route::post('/restoreStudents/{student}/restore', 'Admin\RestoreStudentsController@restore')->name('restorestudents.restore');

    /* Manage Role */
    Route::resource('roles', 'Admin\RolesController', [
        'only' => ['index', 'show', 'edit', 'update',]
    ]);

    /* Dashboard */
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = [
        'name',
    ];

    protected static function boot()
    {
        static::creating(function ($model) {
            $model->code = str_slug($model->name, '-');
        });
    }

    public function permissions()
    {
        return $this->hasMany('App\Permission');
    }

    //refer to Admin model
    public function user()
    {
        return $this->hasMany('App\Admin');
    }

    public static function getRules()
    {
        return [
            'name' => 'required|regex:/^[a-zA-Z]+$/u|max:30',
        ];
    }

    public function getCreatedAtAttribute($value)
    {
        return $this->asDateTime($value)->tz(config('app.app_sms.user_timezone'));
    }

    public function getUpdatedAtAttribute($value)
    {
        return $this->asDateTime($value)->tz(config('app.app_sms.user_timezone'));
    }
}

app/Http/Controllers/Admin/RolesController.php
<?php
/*
* 2018-03-17, at the moment, does not allow create and deleted
*/
namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Validator;
use App\Http\Controllers\Controller;
use App\Role;
use App\Permission;

class RolesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->middleware('is.superadmin');
        $this->middleware('denied.superadmin.edit.own.permissions')->only('edit');
        $this->middleware('admin.has.permissions');
    }

    public function index()
    {
        $roles = Role::all();

        return view('admin.roles.index', compact('roles'));
    }

    public function show(Role $role)
    {
        $permission_labels = Permission::getLabels();

        return view('admin.roles.show', compact('role', 'permission_labels'));
    }

    public function edit(Role $role)
    {
        $permission_labels = Permission::getLabels();

        return view('admin.roles.edit', compact('role', 'permission_labels'));
    }

    public function update(Role $role, Request $request)
    {
        $permissions = $role->permissions;

        $validator = Validator::make(
            $request->all(),
            $this->getModelsRules()
        )->after(function ($validator) use ($request, $permissions) {
            if (count($request->input('Permission.*.enabled')) != $permissions->count()) {
                $validator
                    ->errors()
                    ->add('input_size_not_match_db_rows_size', 'There is an attempt of suspected action.');
            }
        })
        ->validate();

        foreach ($permissions as $i => $permission) {
            $permission->enabled = $request->input('Permission.' . $i . '.enabled');
            $permission->save();
        }

        flash('Successfully updated  roles')->success();

        return redirect()->route('roles.show', $role->id);
    }

    public function getModelsRules()
    {
        return [
            'Permission.*.enabled' => 'required|boolean',
        ];
    }
}

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
          Edit Role
        </h1>
    </section>
    <section class="content">
        <div class="box">
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="col-md-12">
                                @include('layouts.errors._form_errors_summary')
                            </div>
                            {!! Form::model($role, ['route' => ['roles.update', $role->id], 'method' => 'patch']) !!}
                                <div class="col-md-12">
                                    <div class="table-responsive">
                                        <table class="table table-hover" role="grid" aria-describedby="role_listing">
                                            <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Access Right</th>
                                                <th>Enabled</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                                @if (count($role->permissions) != 0)
                                                    @foreach ($role->permissions as $i => $permission)
                                                        <tr style="{{
                                                            count($errors->get('Permission.' . $i . '.student_id'))?
                                                                'border-left: #dd4b39 5px solid;': '' }}">
                                                            <td>{{ $i + 1 }}</td>
                                                            <td>{{ $permission_labels[$permission->ability] }}</td>
                                                            <td>
                                                                {{
                                                                    Form::checkbox(
                                                                        'permission_enabled[' . $i . ']',
                                                                        $permission->enabled,
                                                                        $permission->enabled,
                                                                        [
                                                                            'data-num' => $i,
                                                                            'class' => 'permission_enabled'
                                                                        ]
                                                                    )
                                                                }}
                                                                {{
                                                                    Form::hidden(
                                                                        'Permission[' . $i . '][enabled]',
                                                                        $permission->enabled? $permission->enabled : 0,
                                                                        [
                                                                            'id' => 'permissions_' . $i
                                                                        ]
                                                                    )
                                                                }}
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                @endif
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    {{
                                        Form::submit('Update', [
                                            'class' => 'btn btn-block btn-primary'
                                        ])
                                    }}
                                </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('page-component')
<script>
$(function () {
    jQuery(function () {
        jQuery('.permission_enabled').click(function (e) {
            var checked = $(this).prop('checked');
            var num = $(this).attr('data-num');

            var el = document.getElementById('permissions_' + num);
            if (checked) {
                el.value = 1;
            } else {
                el.value = 0;
            }
        });
    })();
});
</script>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')

@section('css')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('plugins/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content')
<section class="content-header">
    @include('flash::message')
    <h1>
      Role Listing
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap table-responsive">
                        <table class="table table-bordered table-hover dataTable" role="grid" aria-describedby="role_listing">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Created At</th>
                                <th>Updated At</th>
                                <th>View</th>
                                <th>Edit</th>
                            </tr>
                            </thead>
                            <tbody>
                                @if ($roles->isEmpty() == false)
                                    @foreach ($roles as $i => $role)
                                        <tr>
                                            <td>{{ $i + 1 }}</td>
                                            <td>{{ $role->name }}</td>
                                            <td>{{ $role->created_at }}</td>
                                            <td>{{ $role->updated_at }}</td>
                                            <td><a href="{{ route('roles.show', $role->id) }}">View<a></td>
                                            <td><a href="{{ route('roles.edit', $role->id) }}">Edit<a></td>
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('js')
<!-- DataTables -->
<script src="{{ asset('plugins/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<script>
  jQuery(function () {
    jQuery('.dataTable').DataTable()
  })();
</script>
@endsection

resources/views/admin/roles/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        @include('flash::message')
        <h1>
          View Role
        </h1>
    </section>
    <section class="content">
        <div class="box">
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="panel">
                        <div class="panel-body">
                            <div class="col-md-12">
                                @include('layouts.errors._form_errors_summary')
                            </div>
                            <div class="form-group col-md-12">
                                {{
                                    Form::label('Role[Name]', 'Role name', [
                                        'class' => 'control-label'
                                    ])
                                }}
                                <p>
                                    {{ $role->name }}
                                </p>
                            </div>
                            <div class="form-group col-md-6">
                                {{
                                    Form::label('Role[created_at]', 'Created At', [
                                        'class' => 'control-label'
                                    ])
                                }}
                                <p>
                                    {{ $role->created_at }}
                                </p>
                            </div>
                            <div class="form-group col-md-6">
                                {{
                                    Form::label('Role[updated_at]', 'Updated At', [
                                        'class' => 'control-label'
                                    ])
                                }}
                                <p>
                                    {{ $role->updated_at }}
                                </p>
                            </div>
                            <div class="col-md-12">
                                <div class="box">
                                    <div class="box-body">
                                        <div class="table-responsive">
                                            <table class="table table-hover" role="grid" aria-describedby="student_listing">
                                                <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Access Right</th>
                                                    <th>Enabled</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                    @if ($role->permissions->isEmpty() == false)
                                                        @foreach ($role->permissions as $i => $permission)
                                                            <tr>
                                                                <td>{{ $i + 1 }}</td>
                                                                <td>{{ $permission_labels[$permission->ability] }}</td>
                                                                <td>
                                                                    @if ($permission->enabled == true)
                                                                        <i class="fa fa-check" aria-hidden="true" style="color: #4CAF4F"></i>
                                                                    @else
                                                                        <i class="fa fa-times" aria-hidden="true" style="color: #f44336"></i>
                                                                    @endif
                                                                </td>
                                                            </tr>
                                                        @endforeach
                                                    @endif
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-block btn-primary" aria-label="Left Align">
                                    Edit
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection