routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::prefix('parent')->name('parent.')->group(function () {
    Route::get('/inactive', 'Parent\DashboardController@inactive')->name('inactive');

    Route::get('/', 'Parent\DashboardController@index')->name('dashboard');

    Route::prefix('children')->group(function () {
        Route::get('/info', 'Parent\ChildrenController@profile')->name('children.profile');
        Route::get('/activities', 'Parent\ChildrenController@activities')->name('children.activities');
        Route::get('/attendances', 'Parent\ChildrenController@attendances')->name('children.attendances'); //Listing
    });

    Route::prefix('pick_ups')->group(function () {
        Route::get('history', 'Parent\PickUpsController@history')->name('pick_ups.history');
        Route::post('{id}/cancel/', 'Parent\PickUpsController@cancel')->name('pick_ups.cancel');
    });

    Route::resource('pick_ups', 'Parent\PickUpsController', ['only' => [
        'create', 'store', 'show'
    ]]);
});

Route::prefix('admin')->group(function () {
    /* Login/Logout */
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    /* Reset Password */
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

    /* Manage Student*/
    Route::resource('students', 'Admin\StudentsController');
    Route::resource('students.activities', 'Admin\StudentsActivitiesController');

    /* Manage Attendance */
    Route::resource('attendances', 'Admin\AttendancesController');

    /* Manage Student Attendances */
    Route::resource('students.attendances', 'Admin\StudentsAttendancesController', ['only' => [
        'index',
    ]]);

    /* Manage Pick Up */
    Route::resource('pick_ups', 'Admin\PickUpsController', [
        'only' => ['index', 'show']
    ]);

    /* Manage Restore Students */
    Route::get('/restoreStudents', 'Admin\RestoreStudentsController@index')->name('restorestudents.index');
    Route::get('/restoreStudents/{student}', 'Admin\RestoreStudentsController@show')->name('restorestudents.show');
    Route::post('/restoreStudents/{student}/restore', 'Admin\RestoreStudentsController@restore')->name('restorestudents.restore');

    /* Manage Role */
    Route::resource('roles', 'Admin\RolesController', [
        'only' => ['index', 'show', 'edit', 'update',]
    ]);

    /* Dashboard */
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
});

app/PickUp.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PickUp extends Model
{
    /*
    * prevent laravel try to set updated_at column value,
    * and throw errors
    */
    const UPDATED_AT = null;

    /*
    * define column(s) default value
    */
    protected $attributes = [
        'status' => 'active',
    ];

    protected $fillable = [
        'submit_date',
        'driver_name',
        'vehicle_plate_num',
        'relationship',
        'comment',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'cancel_at',
    ];

    public function student()
    {
        return $this->belongsTo('App\Student');
    }

    public static function getStatusRange()
    {
        return [
            'active',
            'cancel',
        ];
    }

    public static function getRules()
    {
        return [
            'driver_name' => 'required|max:40',
            'vehicle_plate_num' => 'required|max:20',
            'relationship' => 'required|max:20',
            'comment' => 'nullable|max:255',
        ];
    }

    public function getCreatedAtAttribute($value)
    {
        return $this->asDateTime($value)->tz(config('app.app_sms.user_timezone'));
    }

    public function getCancelAtAttribute($value)
    {
        if ($value != null) {
            return $this->asDateTime($value)->tz(config('app.app_sms.user_timezone'));
        }
    }
}

app/Http/Controllers/Admin/PickUpsController.php
<?php
/*
* CURD
* - Cannot create (parent right)
* - Cannot Edit (nobody has right)
* - Cannot deleted and void  (parent right)
* - Can read
*/
namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\PickUp;
use Carbon\Carbon;

class PickUpsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->middleware('admin.has.permissions');
    }

    public function index(Request $request)
    {
        $filter_date_meta = $this->getFilterDate($request);
        $filter_date = $filter_date_meta['filter_date'];
        $pick_ups = PickUp::with('student')->has('student')->whereBetween(
            'submit_date',
            [
                $filter_date_meta['startOfDay'],
                $filter_date_meta['endOfDay'],
            ]
        )
        ->orderBy('submit_date', 'DESC')
        ->orderBy('created_at', 'DESC')
        ->get();

        return view('admin.pick_ups.index', compact('pick_ups'));
    }

    public function show(PickUp $pick_up)
    {
        return view('admin.pick_ups.show', compact('pick_up'));
    }

    private function getFilterDate(Request $request)
    {
        if ($request->has('filter_date')) {
            $validate = $this->validate($request, [
                'filter_date' => 'date',
            ]);
            $date = Carbon::parse($validate['filter_date']);
        } else {
            $date = Carbon::today();
        }

        $startOfDay = $date->toDateTimeString();
        $endOfDay = $date->endOfDay()->toDateTimeString();
        $filter_date = $date->toDateString();

        return compact('startOfDay', 'endOfDay', 'filter_date');
    }
}

app/Http/Controllers/Parent/PickUpsController.php
<?php
/*
- Only one active pick up form is allowed per days,
- Pick up form is not allowed to be edited or deleted.
- Only need methods of:
    - history - history or active pick up form
    - show - view single pick up form in detail
    - create
    - store
    - cancel
*/
namespace App\Http\Controllers\Parent;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreStudentPickUpRequest;

use App\PickUp;
use Auth;
use Carbon\Carbon;

class PickUpsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('student.status');
    }

    public function show(Request $request)
    {
        $pick_up = PickUp::where('student_id', Auth::user()->student->id)
            ->where('id', $request->pick_up)
            ->firstOrFail();

        return view('parent.pick_up.show', compact('pick_up'));
    }

    public function create()
    {
        $today_date = Carbon::today()->toDateString();

        $today_pick_ups = PickUp::where('student_id', Auth::user()->student->id)
            ->where('submit_date', $today_date)
            ->orderBy('created_at', 'DESC')
            ->get();

        $active_today_pick_up = $today_pick_ups
            ->where('status', 'active')
            ->all();

        $pick_up = new PickUp;
        $pick_up->submit_date = $today_date;

        return view('parent.pick_up.create',
            compact(
                'today_pick_ups',
                'active_today_pick_up',
                'pick_up',
                'today_date'
            )
        );
    }

    public function store(StoreStudentPickUpRequest $request)
    {
        $active_today_pick_up = PickUp::where('student_id', Auth::user()->student->id)
            ->where('submit_date', Carbon::today()->toDateString())
            ->where('status', 'active')
            ->count();

        if ($active_today_pick_up > 0) {
            abort(404); // only one active pick up form is allowed per day
        }

        $pick_up = new PickUp;
        $pick_up->fill($request->all());
        $pick_up->submit_date = Carbon::today()->toDateString();
        Auth::user()->student->pick_ups()->save($pick_up);

        flash('Successfully submit pick up form.')->success();

        return redirect()->route('parent.pick_ups.create');
    }

    public function cancel(Request $request)
    {
        $pick_up = PickUp::where('student_id', Auth::user()->student->id)
            ->findOrFail($request->id);
        $pick_up->status = 'cancel';
        $pick_up->cancel_at = Carbon::now()->toDateTimeString();
        $pick_up->save();

        flash('Successfully cancel selected pick up form.')->success();

        return redirect()->route('parent.pick_ups.create');
    }

    /*
    * List all pick up forms (filter by year)
    * NOTE: filter by year will be implement later
    */
    public function history()
    {
        //$year =  Carbon::now()->year;
        $pick_ups = PickUp::where('student_id', Auth::user()->student->id)
            //->whereYear('submit_date', '=', $year)
            ->orderBy('submit_date', 'DESC')
            ->orderBy('created_at', 'DESC')
            ->get();

        return view(
            'parent.pick_up.history',
            compact('pick_ups')
        );
    }
}

resources/views/admin/pick_ups/index.blade.php
@extends('layouts.app')

@section('css')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('plugins/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content')
<section class="content-header">
    <h1>
      Pick Up Submitted Forms By Days
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            @include(
                'layouts.form._filter_date',
                [
                    'header_title' => 'Filter pick up submitted forms by day',
                    'route_params' => 'pick_ups.index',
                    'filter_date_param' => 'filter_date',
                    'filter_date_param_placholder' => 'Filter pick up submitted forms by day',
                ]
            )
            <div class="box">
                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap table-responsive">
                        <table class="table table-bordered table-hover dataTable" role="grid" aria-describedby="pick_ups_submitted_form_listing_by_month">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Student</th>
                                <th>Driver</th>
                                <th>Vechicle Plate Num</th>
                                <th>Relationship</th>
                                <th>Comment</th>
                                <th>Status</th>
                                <th>Cancel At</th>
                                <th>View</th>
                            </tr>
                            </thead>
                            <tbody>
                                @if ($pick_ups->isEmpty() == false)
                                    @foreach ($pick_ups as $i => $pick_up)
                                        <tr>
                                            <td>{{ $i + 1 }}</td>
                                            <td>{{ $pick_up->student->name }}</td>
                                            <td>{{ $pick_up->driver_name }}</td>
                                            <td>{{ $pick_up->vehicle_plate_num }}</td>
                                            <td>{{ $pick_up->relationship }}</td>
                                            <td>{{ str_limit($pick_up->comment, 10) }}</td>
                                            <td>{{ $pick_up->status }}</td>
                                            <td>{{ $pick_up->cancel_at? $pick_up->cancel_at : '-'  }}</td>
                                            <td><a href="{{ route('pick_ups.show', $pick_up->id) }}">View<a></td>
                                        </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection


@section('page-component')
<!-- Datepicker -->
<link rel="stylesheet" href="{{ asset('plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" media="screen" title="no title" />
<script src="{{ asset('plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('plugins/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('plugins/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

<script>
  jQuery(function () {
    jQuery('.dataTable').DataTable();

    jQuery('#datepicker').datepicker({
        autoclose: true,
        format: 'yyyy-mm-dd',
        todayBtn: 'linked'
    });
  })();
</script>
@endsection

resources/views/admin/pick_ups/show.blade.php
@extends('layouts.app')

@section('content')
<section class="content-header">
    <h1>
      Pick Up
    </h1>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group col-md-6">
                        {{
                            Form::label('submit_date', 'Submit Date', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p>{{ $pick_up->submit_date }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        {{
                            Form::label('student_name', 'Student', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p><a href="{{ route('students.show', $pick_up->student->id )}}">{{ $pick_up->student->name }}</a></p>
                    </div>
                    <div class="form-group col-md-6">
                        {{
                            Form::label('driver_name', 'Driver Name', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p>{{ $pick_up->driver_name }}</p>
                    </div>

                    <div class="form-group col-md-6">
                        {{
                            Form::label('vehicle_plate_num', 'Vehicle Plate Num', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p>{{ $pick_up->vehicle_plate_num }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        {{
                            Form::label('relationship', 'Relationship', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p>{{ $pick_up->relationship }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        {{
                            Form::label('status', 'Status', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p>{{ $pick_up->status }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        {{
                            Form::label('created_at', 'Created at', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p>{{ $pick_up->created_at }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        {{
                            Form::label('cancel_at', 'Cancel at', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p>{{ $pick_up->cancel_at }}</p>
                    </div>
                    <div class="form-group col-md-12">
                        {{
                            Form::label('comment', 'Comment', [
                                'class' => 'control-label'
                            ])
                        }}
                        <p>{{ $pick_up->comment? $pick_up->comment : '-' }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection