routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::prefix('parent')->name('parent.')->group(function () {
    Route::get('/inactive', 'Parent\DashboardController@inactive')->name('inactive');

    Route::get('/', 'Parent\DashboardController@index')->name('dashboard');

    Route::prefix('children')->group(function () {
        Route::get('/info', 'Parent\ChildrenController@profile')->name('children.profile');
        Route::get('/activities', 'Parent\ChildrenController@activities')->name('children.activities');
        Route::get('/attendances', 'Parent\ChildrenController@attendances')->name('children.attendances'); //Listing
    });

    Route::prefix('pick_ups')->group(function () {
        Route::get('history', 'Parent\PickUpsController@history')->name('pick_ups.history');
        Route::post('{id}/cancel/', 'Parent\PickUpsController@cancel')->name('pick_ups.cancel');
    });

    Route::resource('pick_ups', 'Parent\PickUpsController', ['only' => [
        'create', 'store', 'show'
    ]]);
});

Route::prefix('admin')->group(function () {
    /* Login/Logout */
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    /* Reset Password */
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

    /* Manage Student*/
    Route::resource('students', 'Admin\StudentsController');
    Route::resource('students.activities', 'Admin\StudentsActivitiesController');

    /* Manage Attendance */
    Route::resource('attendances', 'Admin\AttendancesController');

    /* Manage Student Attendances */
    Route::resource('students.attendances', 'Admin\StudentsAttendancesController', ['only' => [
        'index',
    ]]);

    /* Manage Pick Up */
    Route::resource('pick_ups', 'Admin\PickUpsController', [
        'only' => ['index', 'show']
    ]);

    /* Manage Restore Students */
    Route::get('/restoreStudents', 'Admin\RestoreStudentsController@index')->name('restorestudents.index');
    Route::get('/restoreStudents/{student}', 'Admin\RestoreStudentsController@show')->name('restorestudents.show');
    Route::post('/restoreStudents/{student}/restore', 'Admin\RestoreStudentsController@restore')->name('restorestudents.restore');

    /* Manage Role */
    Route::resource('roles', 'Admin\RolesController', [
        'only' => ['index', 'show', 'edit', 'update',]
    ]);

    /* Dashboard */
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
});

resources/views/layouts/section/content.blade.php
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	@yield('content')
</div>

resources/views/layouts/section/header.blade.php
<?php
if (Auth::guard('web')->check() == 1) {
    // parent route
    $logo_route = route('parent.dashboard');
    $logout_route = route('logout');
    $login_name = Auth::user()->profile_name;
} elseif (Auth::guard('admin')->check() == 1) {
    // admin route
    $logo_route = route('admin.dashboard');
    $logout_route = route('admin.logout');
    $login_name = Auth::user()->name;
}
?>

<header class="main-header">

        <!-- Logo -->
    <a href="{{ $logo_route }}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">
            <b>SMS</b>
        </span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">
            <b>SMS</b>
        </span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span>
                            {{ $login_name }}
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-footer">
                            <div class="pull-right">
                                <a href="{{ $logout_route }}"
                                    class="btn btn-default btn-flat"
                                    onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                    Sign out
                                </a>

                            <form id="logout-form"
                                action="{{ $logout_route }}"
                                method="POST"
                                style="display: none;">
                                {{ csrf_field() }}
                            </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/section/sidebar.blade.php
<aside class="main-sidebar">
<!-- sidebar -->
<section class="sidebar">
<!-- sidebar menu -->
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        @if (Auth::guard('admin')->check() == 1 and
            Auth::guard('web')->check() == 0)
        <li class="active">
            <a href="{{ route('admin.dashboard' )}}">
                <i class="fa fa-th"></i> <span>Dashboard</span>
            </a>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-graduation-cap"></i> <span>Students</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="{{ route('students.index') }}">
                        <i class="fa fa-list-ol"></i>
                        Students List
                    </a>
                </li>
                <li>
                    <a href="{{ route('students.create') }}">
                        <i class="fa fa-plus"></i>
                        Add New Student
                    </a>
                </li>
                <li>
                    <a href="{{ route('restorestudents.index') }}">
                        <i class="fa fa-stack-overflow"></i>
                        Restore Students
                    </a>
                </li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-location-arrow"></i> <span>Attendances</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="{{ route('attendances.index') }}">
                        <i class="fa fa-list-ol"></i>
                        Attendances List
                    </a>
                </li>
                <li>
                    <a href="{{ route('attendances.create') }}">
                        <i class="fa fa-plus"></i>
                        Generate Attendance
                    </a>
                </li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-car"></i> <span>Pick Ups</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="{{ route('pick_ups.index') }}">
                        <i class="fa fa-list-ol"></i>
                        Pick Ups List
                    </a>
                </li>
            </ul>
        </li>
        <li class="header">Admin Setting</li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-user-circle-o"></i> <span>Roles</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="{{ route('roles.index') }}">
                        <i class="fa fa-list-ol"></i>
                        Roles List
                    </a>
                </li>
            </ul>
        </li>
        @endif

        @if (Auth::guard('web')->check() == 1 and
        Auth::guard('admin')->check() == 0)
        <li class="active">
            <a href="{{ route('parent.dashboard' )}}">
                <i class="fa fa-th"></i> <span>Dashboard</span>
            </a>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-graduation-cap"></i> <span>Children</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="{{ route('parent.children.profile') }}">
                        <i class="fa fa-child"></i>
                        profile
                    </a>
                </li>
                <li>
                    <a href="{{ route('parent.children.activities') }}">
                        <i class="fa fa-life-ring"></i>
                        Activities
                    </a>
                </li>
                <li>
                    <a href="{{ route('parent.children.attendances') }}">
                        <i class="fa fa-location-arrow"></i>
                        Attendances
                    </a>
                </li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-car"></i> <span>Pick Up</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li>
                    <a href="{{ route('parent.pick_ups.create') }}">
                        <i class="fa fa-file-text-o"></i>
                        Pick Up Form
                    </a>
                </li>
                <li>
                    <a href="{{ route('parent.pick_ups.history') }}">
                        <i class="fa fa-list-alt"></i>
                        Pick Up Form History
                    </a>
                </li>
            </ul>
        </li>
    @endif
    </ul>
</section>
<!-- /.sidebar -->
</aside>