routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::prefix('parent')->name('parent.')->group(function () {
    Route::get('/inactive', 'Parent\DashboardController@inactive')->name('inactive');

    Route::get('/', 'Parent\DashboardController@index')->name('dashboard');

    Route::prefix('children')->group(function () {
        Route::get('/info', 'Parent\ChildrenController@profile')->name('children.profile');
        Route::get('/activities', 'Parent\ChildrenController@activities')->name('children.activities');
        Route::get('/attendances', 'Parent\ChildrenController@attendances')->name('children.attendances'); //Listing
    });

    Route::prefix('pick_ups')->group(function () {
        Route::get('history', 'Parent\PickUpsController@history')->name('pick_ups.history');
        Route::post('{id}/cancel/', 'Parent\PickUpsController@cancel')->name('pick_ups.cancel');
    });

    Route::resource('pick_ups', 'Parent\PickUpsController', ['only' => [
        'create', 'store', 'show'
    ]]);
});

Route::prefix('admin')->group(function () {
    /* Login/Logout */
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    /* Reset Password */
    Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
    Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
    Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

    /* Manage Student*/
    Route::resource('students', 'Admin\StudentsController');
    Route::resource('students.activities', 'Admin\StudentsActivitiesController');

    /* Manage Attendance */
    Route::resource('attendances', 'Admin\AttendancesController');

    /* Manage Student Attendances */
    Route::resource('students.attendances', 'Admin\StudentsAttendancesController', ['only' => [
        'index',
    ]]);

    /* Manage Pick Up */
    Route::resource('pick_ups', 'Admin\PickUpsController', [
        'only' => ['index', 'show']
    ]);

    /* Manage Restore Students */
    Route::get('/restoreStudents', 'Admin\RestoreStudentsController@index')->name('restorestudents.index');
    Route::get('/restoreStudents/{student}', 'Admin\RestoreStudentsController@show')->name('restorestudents.show');
    Route::post('/restoreStudents/{student}/restore', 'Admin\RestoreStudentsController@restore')->name('restorestudents.restore');

    /* Manage Role */
    Route::resource('roles', 'Admin\RolesController', [
        'only' => ['index', 'show', 'edit', 'update',]
    ]);

    /* Dashboard */
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Carbon\Carbon;

class Student extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'code',
        'name',
        'dob',
        'dop',
        'language',
        'race',
        'gender',
        'type',
        'registered',
        'father_name',
        'father_contact',
        'mother_name',
        'mother_contact',
        'address1',
        'address2',
        'remarks1',
        'remarks2',
        'remarks3',
        'status',
    ];

    protected $guarded = [
        'id',
        'user_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'registered',
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function activities()
    {
        return $this->hasMany('App\Activity');
    }

    public function pick_ups()
    {
        return $this->hasMany('App\PickUp');
    }

    public function attendances()
    {
        return $this->hasMany('App\AttendanceList');
    }

    public function getTodayActivitiesAttribute()
    {
        $today_date = Carbon::today()->toDateString();
        return $this->activities()
            ->where('timeline', 'LIKE', '%' . $today_date . '%')
            ->orderBy('timeline', 'DESC')
            ->get();
    }

    public static function getStatusRange()
    {
        return [
            'Active',
            'Non-Active',
            'Achieved',
        ];
    }

    public static function getGenderRange()
    {
        return [
            'Male',
            'Female',
        ];
    }

    public static function getRules()
    {
        $status_range = 'required|in:' . implode(",", self::getStatusRange());
        $gender_range = 'max:10|required|in:' . implode(",", self::getGenderRange());

        return [
            'code' => 'required|max:10|unique:students',
            'name' => 'required|max:40',
            'dob' => 'required|date_format:"Y-m-d"',
            'dop' => 'required|max:20',
            'language' => 'nullable|max:20',
            'race' => 'required|max:15',
            'gender' => $gender_range,
            'type' => 'nullable|max:10',
            'registered' => 'required|date_format: "Y-m-d H:i:s"',
            'father_name' => 'required|max:40',
            'father_contact' => 'required|numeric|digits_between:1,30',
            'mother_name' => 'required|max:40',
            'mother_contact' => 'required|numeric|digits_between:1,30',
            'address1' => 'required|max:100',
            'address2' => 'nullable|max:100',
            'remarks1' => 'nullable|max:120',
            'remarks2' => 'nullable|max:120',
            'remarks3' => 'nullable|max:120',
            'status' => $status_range,
        ];
    }

    public static function getCustomMessage()
    {
        return [
            'dop.required' => 'The place of birth field is required.',
            'dop.max' => 'Place of birth may not be greater than 20 characters.',
            'father_contact.max' => 'Father contact no. may not be greater than 30 characters.',
            'mother_contact.max' => 'Mother contact no. may not be greater than 30 characters.',
            'remarks1.max' => 'Health status may not be greater than 120 characters.',
            'remarks2.max' => 'Academic may not be greater than 120 characters.',
            'remarks3.max'=> 'Special remarks may not be greater than 120 characters.',
            'address1.max' => 'Address 1 may not be greater than 120 characters.',
            'address1.required' => 'The address 1 field is required.',
            'address2.max' => 'Address 2 may not be greater than 120 characters.',
            'dob.required' => 'The date of birth field is required.',
            'dob.date_format' => 'Date of birth is in invalid date format.',
            'registered.date_format' => 'Registered date is in invalid date format.',
            'registered.required' => 'The registered date field is required.'
        ];
    }

    public function setRegisteredAttribute($value)
    {
        $this->attributes['registered'] = Carbon::parse($value, config('app.app_sms.user_timezone'))->setTimezone('UTC');
    }

    public function getRegisteredAttribute($value)
    {
        if ($value != null ) {
            return $this->asDateTime($value)->tz(config('app.app_sms.user_timezone'));
        }
    }

    public function getCreatedAtAttribute($value)
    {
        return $this->asDateTime($value)->tz(config('app.app_sms.user_timezone'));
    }

    public function getUpdatedAtAttribute($value)
    {
        return $this->asDateTime($value)->tz(config('app.app_sms.user_timezone'));
    }

    public function getDeletedAtAttribute($value)
    {
        return $this->asDateTime($value)->tz(config('app.app_sms.user_timezone'));
    }
}

app/Http/Controllers/Admin/StudentsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

use App\User;
use App\Student;
use App\Mail\NotifyNewParentAccountLoginDetail;
use App\Http\Requests\StoreStudentRequest;

class StudentsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
        $this->middleware('admin.has.permissions');
    }

    public function index()
    {

        $model = Student::all();

        return view('admin.students.index', compact('model'));
    }

    public function show(Student $student)
    {
        return view('admin.students.show', compact('student'));
    }

    public function create()
    {
        $student = new Student;
        $user = new User;

        return view('admin.students.create', compact('student', 'user'));
    }

    public function store(StoreStudentRequest $request)
    {
        $login_password = str_random(5);
        $user = User::create([
            'username' => $request->username,
            'profile_name' => $request->profile_name,
            'email' => $request->email,
            'password' => Hash::make($login_password),
        ]);
        $student = $user->student()->create($request->except('username', 'profile_name', 'email', 'password'));
        //$student = Student::create($request->all());

        \Mail::to($user)->send(new NotifyNewParentAccountLoginDetail($user, $login_password));

        flash('Successfully create student.')->success();

        //return redirect()->route('students.index',);
        return redirect()->route('students.show', $student->id);
    }

    public function edit(Student $student)
    {
        return view('admin.students.edit', compact('student'));
    }

    public function update(Student $student, Request $request)
    {
        $rules = Student::getRules();

        if (strcasecmp($student->code, $request->code) === 0) { //Mysql case-insensetive by default
            $rules['code'] = 'required|max:10';
        }

        $this->validate($request, $rules, Student::getCustomMessage());
        $student->fill($request->input())->save();

        flash('Successfully update')->success();

        return redirect()->route('students.show', $student->id);
    }

    public function destroy(Student $student)
    {
        $user = $student->user;
        $student_name = $student->name;
        Student::destroy($student->id);
        flash('Successfully delete student: ' . $student_name)->success();

        return redirect()->route('students.index');
    }
}

resources/views/admin/students/inc/_form.blade.php
<div class="form-group col-md-6 {{ count($errors->get('code')) ? 'has-error': '' }}">
    {{
        Form::label('code', 'Code', [
            'class' => 'form-required, control-label'
        ])
    }}
    {{
        Form::text('code', $student->code, [
            'class' => 'form-control',
            'placeholder' => 'Student code'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('name')) ? 'has-error': '' }}">
    {{
        Form::label('name', 'Name', [
            'class' => 'form-required, control-label'
        ])
    }}
    {{
        Form::text('name', $student->name, [
            'class' => 'form-control',
            'placeholder' => 'Student name'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('dob')) ? 'has-error': '' }}">
    {{
        Form::label('dob', 'Date of brith', [
            'class' => 'control-label'
        ])
    }}
    <div class="input-append date form_datetime_date">
        {{
            Form::text('dob', $student->dob, [
                'class' => 'form-control',
                'placeholder' => 'Student date of birth',
                'size' => 16,
            ])
        }}
        <span class="add-on"><i class="icon-th"></i></span>
    </div>
</div>
<div class="form-group col-md-6 {{ count($errors->get('dop')) ? 'has-error': '' }}">
    {{
        Form::label('dop', 'Place of birth', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::text('dop', $student->dop, [
            'class' => 'form-control',
            'placeholder' => 'Student place of birth'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('language')) ? 'has-error': '' }}">
    {{
        Form::label('language', 'Language', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::text('language', $student->language, [
            'class' => 'form-control',
            'placeholder' => 'Student language'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('race')) ? 'has-error': '' }}">
    {{
        Form::label('race', 'Race', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::text('race', $student->race, [
            'class' => 'form-control',
            'placeholder' => 'Student race'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('gender')) ? 'has-error': '' }}">
    {{
        Form::label('gender', 'Gender', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::select(
            'gender',
            [
                'Male' => 'Male',
                'Female' => 'Female',
            ],
            $student->gender,
            [
                'class' => 'form-control',
                'placeholder' => 'Please select',
            ]
        )
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('type')) ? 'has-error': '' }}">
    {{
        Form::label('type', 'Type', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::text('type', $student->type, [
            'class' => 'form-control',
            'placeholder' => 'Student type'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('registered')) ? 'has-error': '' }}">
    {{
        Form::label('registered', 'Registered date', [
            'class' => 'control-label'
        ])
    }}
    <div class="input-append date form_datetime">
        {{
            Form::text('registered', $student->registered, [
                'class' => 'form-control',
                'placeholder' => 'Student registered date'
            ])
        }}
        <span class="add-on"><i class="icon-th"></i></span>
    </div>
</div>
<div class="form-group col-md-6 {{ count($errors->get('status')) ? 'has-error': '' }}">
    {{
        Form::label('status', 'Status', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::select(
            'status',
            [
                'Active' => 'Active',
                'Non-Active' => 'Non-Active',
                'Achieved' => 'Achieved'
            ],
            $student->status,
            [
                'class' => 'form-control',
                'placeholder' => 'Please select',
            ]
        )
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('father_name')) ? 'has-error': '' }}">
    {{
        Form::label('father_name', 'Father name', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::text('father_name', $student->father_name, [
            'class' => 'form-control',
            'placeholder' => 'Student father name'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('father_contact')) ? 'has-error': '' }}">
    {{
        Form::label('father_contact', 'Father contanct no.', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::text('father_contact', $student->father_contact, [
            'class' => 'form-control',
            'placeholder' => 'Student father contanct no.'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('mother_name')) ? 'has-error': '' }}">
    {{
        Form::label('mother_name', 'Mother name', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::text('mother_name', $student->mother_name, [
            'class' => 'form-control',
            'placeholder' => 'Student mother name.'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('mother_contact')) ? 'has-error': '' }}">
    {{
        Form::label('mother_contact', 'Mother contanct no.', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::text('mother_contact', $student->mother_contact, [
            'class' => 'form-control',
            'placeholder' => 'Student mother contanct no.'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('address1')) ? 'has-error': '' }}">
    {{
        Form::label('address1', 'Address 1', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::textarea('address1', $student->address1, [
            'class' => 'form-control',
            'placeholder' => 'Student address 1'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('address2')) ? 'has-error': '' }}">
    {{
        Form::label('address2', 'Address 2', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::textarea('address2', $student->address2, [
            'class' => 'form-control',
            'placeholder' => 'Student address 2'
        ])
    }}
</div>
<div class="form-group col-md-12 {{ count($errors->get('remarks1')) ? 'has-error': '' }}">
    {{
        Form::label('remarks1', 'Health status', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::textarea('remarks1', $student->remarks1, [
            'class' => 'form-control',
            'placeholder' => 'Student health status'
        ])
    }}
</div>
<div class="form-group col-md-12 {{ count($errors->get('remarks2')) ? 'has-error': '' }}">
    {{
        Form::label('remarks2', 'Academic record', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::textarea('remarks2', $student->remarks2, [
            'class' => 'form-control',
            'placeholder' => 'Student academic record'
        ])
    }}
</div>
<div class="form-group col-md-12 {{ count($errors->get('remarks3')) ? 'has-error': '' }}">
    {{
        Form::label('remarks3', 'Special remarks', [
            'class' => 'control-label'
        ])
    }}
    {{
        Form::textarea('remarks3', $student->remarks3, [
            'class' => 'form-control',
            'placeholder' => 'Special remarks'
        ])
    }}
</div>

resources/views/admin/students/inc/_sub_menu.blade.php
<div class="col-md-3">
    <a href="{{ route('students.activities.create', $student->id) }}" class="btn btn-primary btn-block margin-bottom">Compose Activity</a>
    <div class="box box-solid">
        <div class="box-body no-padding">
        <ul class="nav nav-pills nav-stacked">
            <li>
                <a href="{{ route('students.show', $student->id) }}">
                    <i class="fa fa-file-text-o"></i> View Student Info
                </a>
            </li>
            <li>
                <a href="{{ route('students.activities.index', $student->id) }}">
                    <i class="fa fa-life-ring"></i> View Activity
                </a>
            </li>
            <li>
                <a href="{{ route('students.attendances.index', $student->id) }}">
                    <i class="fa fa-location-arrow"></i> View Attendances
                </a>
            </li>
        </ul>
        </div>
    </div>
</div>

resources/views/admin/students/inc/_user_field_form.blade.php
<div class="form-group col-md-12">
    <h3 class="box-title">Parent Login Info:</h3>
</div>
<div class="form-group col-md-6 {{ count($errors->get('username')) ? 'has-error': '' }}">
    {{
        Form::label('username', 'username', [
            'class' => 'form-required, control-label'
        ])
    }}
    {{
        Form::text('username', $user->username, [
            'class' => 'form-control',
            'placeholder' => 'Parent login username'
        ])
    }}
</div>
<div class="form-group col-md-6 {{ count($errors->get('profile_name')) ? 'has-error': '' }}">
    {{
        Form::label('profile_name', 'profile name', [
            'class' => 'form-required, control-label'
        ])
    }}
    {{
        Form::text('profile_name', $user->profile_name, [
            'class' => 'form-control',
            'placeholder' => 'Profle name for login account'
        ])
    }}
</div>
<div class="form-group col-md-12 {{ count($errors->get('email')) ? 'has-error': '' }}">
    {{
        Form::label('email', 'email', [
            'class' => 'form-required, control-label'
        ])
    }}
    {{
        Form::email('email', $user->email, [
            'class' => 'form-control',
            'placeholder' => 'Parent email for resetting password, received email, etc'
        ])
    }}
</div>
<div class="form-group col-md-12">
    <h3 class="box-title">Student Info:</h3>
</div>